### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Kaiserabbas** [Kaiserabbas/Fusion-Bites#42]
https://github.com/Kaiserabbas/Fusion-Bites/projects/1
We are a total of two people working on this project.
1 - @Kaiserabbas 
2- @misikir21

**Comment by V-Blaze** [comment]
Hi @Kaiserabbas , @misikir21 

# Approved 🍏 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![green-lantern-ok](https://user-images.githubusercontent.com/107632780/229644347-63cd2692-a569-4093-9c95-9fad40e2d9f2.gif)

## Highlights
- Kanban board setup correctly✔✔
- Cards are assigned to students :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
